"""add business tables

Revision ID: 0002_business_tables
Revises: 0001_initial
Create Date: 2026-09-23 20:09:25.191918
"""
from __future__ import annotations
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '0002_business_tables'
down_revision: Union[str, None] = '0001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fin_accounts',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('category', sa.String(length=16), nullable=False),
    sa.Column('opening_balance', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('remark', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fin_accounts_category'), 'fin_accounts', ['category'], unique=False)
    op.create_index(op.f('ix_fin_accounts_code'), 'fin_accounts', ['code'], unique=True)
    op.create_index(op.f('ix_fin_accounts_name'), 'fin_accounts', ['name'], unique=False)
    op.create_index(op.f('ix_fin_accounts_status'), 'fin_accounts', ['status'], unique=False)
    op.create_table('fin_reports',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('period', sa.String(length=16), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('data', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('remark', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fin_reports_period'), 'fin_reports', ['period'], unique=False)
    op.create_index(op.f('ix_fin_reports_status'), 'fin_reports', ['status'], unique=False)
    op.create_index(op.f('ix_fin_reports_type'), 'fin_reports', ['type'], unique=False)
    op.create_table('fin_voucher_entries',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('voucher_id', sa.String(length=64), nullable=False),
    sa.Column('account_id', sa.String(length=64), nullable=False),
    sa.Column('direction', sa.String(length=8), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('summary', sa.String(length=512), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fin_voucher_entries_account_id'), 'fin_voucher_entries', ['account_id'], unique=False)
    op.create_index(op.f('ix_fin_voucher_entries_voucher_id'), 'fin_voucher_entries', ['voucher_id'], unique=False)
    op.create_table('fin_vouchers',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('voucher_no', sa.String(length=64), nullable=False),
    sa.Column('voucher_date', sa.String(length=32), nullable=False),
    sa.Column('summary', sa.String(length=512), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('total_debit', sa.Float(), nullable=False),
    sa.Column('total_credit', sa.Float(), nullable=False),
    sa.Column('posted_at', sa.String(length=32), nullable=False),
    sa.Column('remark', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fin_vouchers_status'), 'fin_vouchers', ['status'], unique=False)
    op.create_index(op.f('ix_fin_vouchers_voucher_date'), 'fin_vouchers', ['voucher_date'], unique=False)
    op.create_index(op.f('ix_fin_vouchers_voucher_no'), 'fin_vouchers', ['voucher_no'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fin_vouchers_voucher_no'), table_name='fin_vouchers')
    op.drop_index(op.f('ix_fin_vouchers_voucher_date'), table_name='fin_vouchers')
    op.drop_index(op.f('ix_fin_vouchers_status'), table_name='fin_vouchers')
    op.drop_table('fin_vouchers')
    op.drop_index(op.f('ix_fin_voucher_entries_voucher_id'), table_name='fin_voucher_entries')
    op.drop_index(op.f('ix_fin_voucher_entries_account_id'), table_name='fin_voucher_entries')
    op.drop_table('fin_voucher_entries')
    op.drop_index(op.f('ix_fin_reports_type'), table_name='fin_reports')
    op.drop_index(op.f('ix_fin_reports_status'), table_name='fin_reports')
    op.drop_index(op.f('ix_fin_reports_period'), table_name='fin_reports')
    op.drop_table('fin_reports')
    op.drop_index(op.f('ix_fin_accounts_status'), table_name='fin_accounts')
    op.drop_index(op.f('ix_fin_accounts_name'), table_name='fin_accounts')
    op.drop_index(op.f('ix_fin_accounts_code'), table_name='fin_accounts')
    op.drop_index(op.f('ix_fin_accounts_category'), table_name='fin_accounts')
    op.drop_table('fin_accounts')
    # ### end Alembic commands ###
